#GET http://localhost:5005/api/auth

###
POST http://localhost:5005/api/auth/register
Content-Type: application/json

{
  "username": "cubin1",
  "password": "cubin123"
}

###
POST http://localhost:5005/api/auth/login
Content-Type: application/json

{
  "username": "cubin2",
  "password": "cubin123"
}


###
POST http://localhost:5005/api/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2M2ZmOTIxNTg0M2RkMzRiMWE1NmY1M2YiLCJpYXQiOjE2NzkxMTY1MTZ9.31md06p-X_cX0qYmNea_xrLAeCXvx_12cSzzilBhd0c

{
  "title": "Cubin 2",
  "description": "cubasdGDFWEFSFdqwin1",
  "url": "googFSFl/eweEQWE.e.com",
  "status": "LEARNED"
}

###
GET http://localhost:5005/api/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2M2ZmOTBlODg0M2RkMzRiMWE1NmY1MzYiLCJpYXQiOjE2Nzc2OTMyNzJ9.nmi-P6dB3MbiB7V6GNLzF034c3wb9Ix2QesRL0imyrA


###
PUT http://localhost:5005/api/posts/6416334682a6fe7fce148c68
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2M2ZmOTBlODg0M2RkMzRiMWE1NmY1MzYiLCJpYXQiOjE2Nzc2OTMyNzJ9.nmi-P6dB3MbiB7V6GNLzF034c3wb9Ix2QesRL0imyrA

{
  "title": "CubiOIIIweere",
  "description": "BUUU",
  "url": "GHD",
  "status": "LEARNING"
}

###
DELETE http://localhost:5005/api/posts/64005fc8589d208e99bc8c34
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2M2ZmOTBlODg0M2RkMzRiMWE1NmY1MzYiLCJpYXQiOjE2Nzc2OTMyNzJ9.nmi-P6dB3MbiB7V6GNLzF034c3wb9Ix2QesRL0imyrA


###
GET http://localhost:5005/api/auth
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2M2ZmOTIxNTg0M2RkMzRiMWE1NmY1M2YiLCJpYXQiOjE2NzgzODA5NDJ9.Nl1MJJS3teYXlnw-oTsxhz1-jc4CpxRcNGBhOs4TSlg

